import telebot
import random
import secrets
import string

# 🔑 ضع توكن البوت هنا
TOKEN = "8164008085:AAHmC1Ji7pzU2-1GieUMOWrN5-qWFWcD8Dc"
bot = telebot.TeleBot(TOKEN)

# ===== بيانات الأسماء والدومينات =====
FIRST_NAMES = [
    "James","John","Robert","Michael","William","David","Richard","Joseph","Thomas","Charles",
    "Christopher","Daniel","Matthew","Anthony","Mark","Donald","Steven","Paul","Andrew","Joshua",
    "Mary","Patricia","Jennifer","Linda","Elizabeth","Barbara","Susan","Jessica","Sarah","Karen",
    "Alex","Taylor","Jordan","Casey","Riley","Morgan","Cameron","Avery","Quinn","Rowan"
]
LAST_NAMES = [
    "Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez",
    "Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin"
]
EMAIL_DOMAINS = ["gmail.com", "yahoo.com", "outlook.com", "hotmail.com"]

# ===== أدوات التوليد =====
def generate_name_and_email():
    first = random.choice(FIRST_NAMES)
    last = random.choice(LAST_NAMES)
    number = str(random.randint(10, 99))
    domain = random.choice(EMAIL_DOMAINS)
    email = f"{first.lower()}.{last.lower()}{number}@{domain}"
    full_name = f"{first} {last}"
    return full_name, email

def generate_strong_password(length: int = 14) -> str:
    if length < 8:
        length = 8
    alphabet_upper = string.ascii_uppercase
    alphabet_lower = string.ascii_lowercase
    digits = string.digits
    symbols = "!@#$%^&*()-_=+[]{};:,.<>?/"
    # Ensure at least one from each
    password_chars = [
        secrets.choice(alphabet_upper),
        secrets.choice(alphabet_lower),
        secrets.choice(digits),
        secrets.choice(symbols),
    ]
    all_chars = alphabet_upper + alphabet_lower + digits + symbols
    for _ in range(length - len(password_chars)):
        password_chars.append(secrets.choice(all_chars))
    random.shuffle(password_chars)
    return "".join(password_chars)

def generate_phone_number():
    # +63 then 10 digits (common mobile starts with 9)
    first_digit = "9"
    rest = "".join(secrets.choice(string.digits) for _ in range(9))
    return f"+63{first_digit}{rest}"

# ===== زخرفة النص (fullwidth) =====
def to_fullwidth(text: str) -> str:
    """
    Convert printable ASCII characters (33..126) to their fullwidth Unicode equivalents.
    Spaces are kept as normal spaces for readability.
    """
    out = []
    for ch in text:
        code = ord(ch)
        if 33 <= code <= 126:
            out.append(chr(code + 0xFEE0))
        else:
            out.append(ch)
    return "".join(out)

# ===== بناء الرسالة المزخرفة بالإنجليزية =====
def build_decorated_message(name, email, password, phone):
    # Fancy header/footer and emojis
    header = "✦✦ 𝐆𝐞𝐧𝐞𝐫𝐚𝐭𝐞𝐝 𝐈𝐃 𝐏𝐚𝐜𝐤 ✦✦"
    # Stylize name using fullwidth for a classy decorative look
    fancy_name = to_fullwidth(name)
    # Compose the message in English, decorated
    lines = [
        "╔════════════════════════════════╗",
        f"   {header}",
        "╠════════════════════════════════╣",
        f"  🧑 Name: {fancy_name}",
        f"  ✉️ Email: {email}",
        f"  🔐 Password: `{password}`",
        f"  📱 Phone: {phone}",
        "╚════════════════════════════════╝",
        "✨ Generated by FancyNameBot — Enjoy! ✨"
    ]
    return "\n".join(lines)

# ===== بوت تيليغرام =====
@bot.message_handler(commands=['start'])
def send_welcome(message):
    # 🔗 روابط الأزرار
    dev_url = "https://t.me/XX_VV_88"
    channel_url = "https://t.me/G_L_S_B"

    # ⌨️ إنشاء الكيبورد
    keyboard = types.InlineKeyboardMarkup()
    keyboard.add(
        types.InlineKeyboardButton("👨‍💻 Bot Developer", url=dev_url),
        types.InlineKeyboardButton("📢 Bot Channel", url=channel_url)
    )

    # 🖼️ نص الكابشن (ترحيب + الرسالة الإنجليزية)
    caption_text = (
    "🇵🇭✨ Welcome to the *Philippine Info Generator Bot*! ✨🇵🇭\n\n"
    "🤖 I can generate random Filipino-style identity details for you.\n\n"
    "➡️ Just send */em* to receive:\n"
    "   🧑 Name\n"
    "   ✉️ Email\n"
    "   🔐 Password\n"
    "   📱 Phone Number\n\n"
    "Enjoy using the bot! 🚀"
    )

    # 🖼️ إرسال صورة مع الكابشن والكيبورد
    bot.send_photo(
        chat_id=message.chat.id,
        photo="https://t.me/G_K_L_A_K/8",
        caption=caption_text,
        parse_mode="Markdown",
        reply_markup=keyboard
    )

@bot.message_handler(commands=['em'])
def send_em(message):
    name, email = generate_name_and_email()
    password = generate_strong_password(14)
    phone = generate_phone_number()
    reply = build_decorated_message(name, email, password, phone)
    # Use Markdown so the password is mono-formatted; fullwidth name is safe in Markdown
    bot.reply_to(message, reply, parse_mode="Markdown")

# ===== تشغيل البوت =====
if __name__ == "__main__":
    print("✅ Fancy Telegram bot is running...")
    bot.infinity_polling()
